using System;
using System.Web;
using EPS.Web.Authentication.Configuration;

namespace EPS.Web.Authentication.Abstractions
{
    /// <summary>   
    /// Interface that defines a simple behavior for configuration and implementation of a handler that inspects incoming HttpContext and
    /// generates an IPrincipal if necessary.. 
    /// </summary>
    /// <remarks>   ebrown, 1/3/2011. </remarks>
    public interface IAuthenticator
    {
        /// <summary>   Gets the human-friendly name of the authenticator. </summary>
        /// <value> The name. </value>
        string Name { get; }
        
        /// <summary>   Authenticates a given HttpContextBase, returning a status and IPrincipal if successful. </summary>
        /// <param name="context">  The context. </param>
        /// <returns>   The result generated by inspecting the context. </returns>
        AuthenticationResult Authenticate(HttpContextBase context);
        
        /// <summary>   
        /// Gets the simple base class configuration for the authenticator - implementors are better served to use the one defined in <see
        /// cref="EPS.Web.Authentication.Abstractions.IAuthenticator{T}"/>. 
        /// </summary>
        /// <value> The configuration. </value>
        IAuthenticatorConfiguration Configuration { get; }
    }
    
    /// <summary>   
    /// Generic version of the interface that defines a simple behavior for configuration and implementation of a handler that inspects
    /// incoming HttpContext and generates an IPrincipal if necessary.  Configuration is specialized in this variant. 
    /// </summary>
    /// <remarks>   ebrown, 1/3/2011. </remarks>
    public interface IAuthenticator<out T> : IAuthenticator
        where T : class, IAuthenticatorConfiguration
    {
        /// <summary>   Gets the specialized configuration -- hides Configuration from IAuthenticator. </summary>
        /// <value> The configuration. </value>
        new T Configuration { get; }
    }
}